version: "3"

services:
        pihole:
                container_name: pihole
                image: pihole/pihole:latest
                ports:
                        - 53:53/tcp
                        - 53:53/udp
                        - 67:67/udp
                        - 80:80/tcp
                env_file:
                        - ./env.env
                volumes:
                        - ./pihole:/etc/pihole
                        - ./dnsmasp.d:/etc/dnsmasp.d
                cap_add:
                        - NET_ADMIN
                restart: unless-stopped
