version: '3'

services:
        jellyfin:
                image: jellyfin/jellyfin:latest
                container_name: jellyfin
                network_mode: "host"
                volumes:
                        - ./config:/config
                        - ./cache:/cache
                        # - /path/to/media/dir:/media
                        # - ./path/to/media/dir/two:/media2:ro
                restart: 'unless-stopped'
